[tool.poetry]
name = "pydumpling"
version = "0.1.0"
description = ""
authors = ["cocolato <haiizhu@outlook.com>"]
readme = "README.md"
packages = [{include = "pydumpling/*.py"}]

[tool.poetry.dependencies]
python = ">=2.7, !=3.0.*, !=3.1.*, !=3.2.*"
dill = "^0.3.2"
six = "^1.16.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
