[tool.pdm]
distribution = true

[tool.pdm.build]
includes = ["pydumpling/*.py"]
[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"


[project]
name = "pydumpling"
version = "0.1.2"
description = ""
authors = [
    {name = "cocolato", email = "haiizhu@outlook.com"},
]
dependencies = [
    "dill<1.0.0,>=0.3.2",
    "six<2.0.0,>=1.16.0",
]
requires-python = "!=3.0.*,!=3.1.*,!=3.2.*,>=2.7"
readme = "README.md"
license = {text = "MIT"}
