[tool.poetry]
name = "pydumpling"
version = "0.1.0"
description = ""
authors = ["cocolato <haiizhu@outlook.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
dill = "^0.3.6"
six = "^1.16.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
