name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - {name: '3.13', python: '3.13', os: ubuntu-latest}
          - {name: '3.12', python: '3.12', os: ubuntu-latest}
          - {name: '3.11', python: '3.11', os: ubuntu-latest}
          - {name: '3.10', python: '3.10', os: ubuntu-latest}
          - {name: '3.9', python: '3.9', os: ubuntu-latest}
          - {name: '3.8', python: '3.8', os: ubuntu-latest}
          - {name: '3.7', python: '3.7', os: ubuntu-latest}
    steps:
      # - uses: actions/checkout@v3
      # - name: Set up Python
      #   uses: actions/setup-python@v5
      #   with:
      #     python-version: ${{ matrix.python }}
      #     cache: 'pip'
      # - name: Install uv
      #   run: pip install uv
      # - name: Install dependencies
      #   run: uv pip install .[dev]
      # - name: Run tests
      #   run: pytest --cov=pydumpling --cov-report=term-missing tests/
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install uv
          uv sync --dev
      - name: Test with uv
        run: |
          uv run hatch run test
